name: Build README Dynamically

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    name: Build README
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12.x]
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Setup nodejs version
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node}}
      - name: Install Dependencies
        run: npm ci
      - name: Generate README
        run: npm start
      - name: Commit changes
        run: |-
          git add .
          git config --global user.email "mohammad_aabed@hotmail.com"
          git config --global user.name "mhmdabed11"
          git commit -m "Updated README"
          git push origin master
